### ISSUE TITLE
Dilbert RSS results in 403

### ISSUE THREAD

**Issue by deadratfink** [mattiasrunge/daily-comic.js#1]
Hi Mattias,

maybe you haven't noticed that so far, but http://rss.latunyi.com/dilbert.rss is "broken" now (HTTP 403). At https://chrisbenard.net/2013/06/28/how-to-fix-the-dilbert-com-rss-feed/ I found a new feed which can be used, as well as other comic RSS feeds which could be utilized to enhance this cool module.

**Comment by mattiasrunge** [comment]
Sorry for the really really late response on this... github does not give me notifications :(
Have released a new version.
